In [19]:
import numpy as np
from numpy.fft import fft, ifft
import scipy.fft as spfft
import matplotlib.pyplot as plt
from numpy import convolve


In [23]:
u = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
fft(u)

array([45.  +0.j        , -4.5+12.36364839j, -4.5 +5.36289117j,
       -4.5 +2.59807621j, -4.5 +0.79347141j, -4.5 -0.79347141j,
       -4.5 -2.59807621j, -4.5 -5.36289117j, -4.5-12.36364839j])

In [15]:
v = u.copy()

In [22]:
n = len(u) + len(v) - 1
u.resize(n)
v.resize(n)

ifft(fft(u) * fft(v))

array([  1.-2.44444084e-15j,   4.-3.84677341e-15j,  10.-1.88002722e-15j,
        20.-1.11130229e-15j,  35.-8.35059495e-15j,  56.-8.99043252e-15j,
        84.+3.91996693e-15j, 120.-2.99780923e-16j, 147.-3.72005675e-15j,
       164.+3.91996693e-15j, 170.+6.80796849e-15j, 164.+3.38769267e-15j,
       145.-1.11130229e-15j, 112.+7.17947687e-15j,  64.+6.53963930e-15j])

In [20]:
convolve(u, v)

array([  1,   4,  10,  20,  35,  56,  84, 120, 147, 164, 170, 164, 145,
       112,  64])

In [ ]:
"